name: flutter_training
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  build_runner: ^2.4.4
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.6
  freezed: ^2.3.4
  freezed_annotation: ^2.2.0
  json_serializable: ^6.7.0
  hooks_riverpod: ^2.3.4
  flutter_gen: ^5.3.1
  flutter_svg: ^2.0.7
  dio: ^5.2.1+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_gen_runner:

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/thumbnail/
    - assets/icons/

flutter_gen:
  integrations:
    flutter_svg: true