import '../gen/assets.gen.dart';
import 'package:flutter/material.dart';

List<String> appbarIconNameList = [
  'OMG!',
  'Rooms',
  'Tiny homes',
  'Creative spaces',
  'Iconic cities',
  'Mansions',
  'Cabins',
  'Beachfront',
  'Amazing views',
  'Grand pianos',
  'Houseboats',
  'Adapted',
  'Windmills',
  'Amazing pools',
  'A-frames',
  'Yurts',
  'Barns',
  'Treehouses',
  'Design',
  'Lake',
  'Bed & breakfasts',
  'Surfing',
  'Lakefront',
  'National parks',
  'Castles',
  'Trending',
  'Camping',
  'Domes',
  'Containers',
  'Ryokans',
  'Hanoks',
  'Tropical',
  'Caves',
  'Skiing',
  'Arctic',
  'Earth homes',
  'Countryside',
  'Vineyards',
  'Historical homes',
  'Farms',
  'Play',
  'Campers',
  'Islands',
  'New',
  'Golfing',
  'Luxe',
  "Chef's kitchens",
  'Top of the world',
  'Cycladic homes',
  'Ski-in/out',
  'Casas particulares',
  'Minsus',
  "Shepherd's huts",
  'Towers',
  'Desert',
  'Boats',
  'Off-the-grid',
  'Riads',
  'Dammusi',
  'Trulli',
  'Beach',
  'dummy1',
  'dummy2',
  'dummy3',
  'dummy4',
];

List<Image> appbarIconImageList = [
  Assets.images.img1.image(scale: 2),
  Assets.images.img2.image(scale: 2),
  Assets.images.img3.image(scale: 2),
  Assets.images.img4.image(scale: 2),
  Assets.images.img5.image(scale: 2),
  Assets.images.img6.image(scale: 2),
  Assets.images.img7.image(scale: 2),
  Assets.images.img8.image(scale: 2),
  Assets.images.img9.image(scale: 2),
  Assets.images.img10.image(scale: 2),
  Assets.images.img11.image(scale: 2),
  Assets.images.img12.image(scale: 2),
  Assets.images.img13.image(scale: 2),
  Assets.images.img14.image(scale: 2),
  Assets.images.img15.image(scale: 2),
  Assets.images.img16.image(scale: 2),
  Assets.images.img17.image(scale: 2),
  Assets.images.img18.image(scale: 2),
  Assets.images.img19.image(scale: 2),
  Assets.images.img20.image(scale: 2),
  Assets.images.img21.image(scale: 2),
  Assets.images.img22.image(scale: 2),
  Assets.images.img23.image(scale: 2),
  Assets.images.img24.image(scale: 2),
  Assets.images.img25.image(scale: 2),
  Assets.images.img26.image(scale: 2),
  Assets.images.img27.image(scale: 2),
  Assets.images.img28.image(scale: 2),
  Assets.images.img29.image(scale: 2),
  Assets.images.img30.image(scale: 2),
  Assets.images.img31.image(scale: 2),
  Assets.images.img32.image(scale: 2),
  Assets.images.img33.image(scale: 2),
  Assets.images.img34.image(scale: 2),
  Assets.images.img35.image(scale: 2),
  Assets.images.img36.image(scale: 2),
  Assets.images.img37.image(scale: 2),
  Assets.images.img38.image(scale: 2),
  Assets.images.img39.image(scale: 2),
  Assets.images.img40.image(scale: 2),
  Assets.images.img41.image(scale: 2),
  Assets.images.img42.image(scale: 2),
  Assets.images.img43.image(scale: 2),
  Assets.images.img44.image(scale: 2),
  Assets.images.img45.image(scale: 2),
  Assets.images.img46.image(scale: 2),
  Assets.images.img47.image(scale: 2),
  Assets.images.img48.image(scale: 2),
  Assets.images.img49.image(scale: 2),
  Assets.images.img50.image(scale: 2),
  Assets.images.img51.image(scale: 2),
  Assets.images.img52.image(scale: 2),
  Assets.images.img53.image(scale: 2),
  Assets.images.img54.image(scale: 2),
  Assets.images.img55.image(scale: 2),
  Assets.images.img56.image(scale: 2),
  Assets.images.img57.image(scale: 2),
  Assets.images.img58.image(scale: 2),
  Assets.images.img59.image(scale: 2),
  Assets.images.img60.image(scale: 2),
  Assets.images.img61.image(scale: 2),
  Assets.images.img62.image(scale: 2),
  Assets.images.img63.image(scale: 2),
  Assets.images.img64.image(scale: 2),
  Assets.images.img65.image(scale: 2),
];
